### ISSUE TITLE
?.  ?? 这种运算符都不支持。项目启动不了

### ISSUE THREAD

**Issue by DreamZhang97** [levi-Ma/preset-uni-vue3#2]
const setup = (plugin) => plugin.esbuild?.setup ?? ((build2) => {
                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/zjh/studying/uni-app/preset-uni-vue3/node_modules/unplugin-auto-import/dist/chunk-BRLMGO66.cjs:7:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by DreamZhang97** [comment]
代码就是你的，我直接拉下来，下载依赖，启动项目， 就报上面的错误。你发的参考问题，我当时也看了，我在下面也留评论了，不行。

**Comment by levi-Ma** [comment]
H5还是小程序

**Comment by levi-Ma** [comment]
暂时用npm install 和npm run dev:h5/mp-weixin，u-draw-poster这个包换名字了，pnpm安装的包有问题

**Comment by levi-Ma** [comment]
package.json 删除 u-draw-poster 这个包后 pnpm install 和 pnpm dev:h5/mp-wexin 正常了，新包改成了u-draw，明后天我会传一个新版进来，感谢。
